# Generated by Django 5.0.3 on 2026-03-27 08:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BringList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Datum')),
                ('slug', models.SlugField(unique=True)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('edit_mode', models.CharField(choices=[('free', 'Jeder kann jeden Eintrag bearbeiten'), ('own', 'Nur eigene Einträge bearbeiten (Session)'), ('insert_only', 'Nur hinzufügen, kein Bearbeiten')], default='own', max_length=20, verbose_name='Bearbeitungsmodus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bring-Liste',
                'verbose_name_plural': 'Bring-Listen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BringItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Was wird mitgebracht')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Menge')),
                ('contributor_name', models.CharField(max_length=255, verbose_name='Name')),
                ('note', models.TextField(blank=True, verbose_name='Anmerkung')),
                ('edit_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bring_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bring_list.bringlist')),
            ],
            options={
                'verbose_name': 'Eintrag',
                'verbose_name_plural': 'Einträge',
                'ordering': ['created_at'],
            },
        ),
    ]
