# Generated by Django 5.0.3 on 2026-03-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bring_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bringlist',
            name='show_quantity',
            field=models.BooleanField(default=True, verbose_name='Mengenfeld anzeigen'),
        ),
    ]
