# Generated by Django 5.0.3 on 2026-03-02 20:06

import uuid
from django.db import migrations


def populate_uuids(apps, schema_editor):
    """Generate UUIDs for existing Shift and Task records."""
    Shift = apps.get_model('festival', 'Shift')
    Task = apps.get_model('festival', 'Task')

    # Populate Shift UUIDs
    for shift in Shift.objects.filter(id__isnull=True):
        shift.id = uuid.uuid4()
        shift.save()

    # Populate Task UUIDs
    for task in Task.objects.filter(id__isnull=True):
        task.id = uuid.uuid4()
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_alter_shift_id_alter_task_id'),
    ]

    operations = [
        migrations.RunPython(populate_uuids),
    ]

