# Generated by Django 5.0.3 on 2026-03-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0003_populate_uuids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='date',
        ),
        migrations.AddField(
            model_name='festival',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
