# Generated by Django 5.0.3 on 2026-03-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0006_add_konzertmeister_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='masked',
            field=models.BooleanField(default=False),
        ),
    ]
