# Generated by Django 5.0.3 on 2026-03-10 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0007_participant_masked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='attended',
        ),
    ]
