# Generated by Django 5.0.3 on 2026-03-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(default='hauptkapelle@bmk-buggingen.de', help_text='E-Mail-Adresse oder Verteiler für den regulären Versand', max_length=254, verbose_name='Empfänger')),
                ('from_email', models.EmailField(default='news@bmk-buggingen.de', max_length=254, verbose_name='Absender')),
                ('km_appointments_url', models.URLField(blank=True, verbose_name='Konzertmeister Termine-URL')),
                ('km_requests_url', models.URLField(blank=True, verbose_name='Konzertmeister Anfragen-URL')),
            ],
            options={
                'verbose_name': 'Newsletter-Einstellung',
                'verbose_name_plural': 'Newsletter-Einstellungen',
            },
        ),
        migrations.AddField(
            model_name='weeklymails',
            name='events',
            field=models.TextField(blank=True, verbose_name='Veranstaltungen'),
        ),
        migrations.AddField(
            model_name='weeklymails',
            name='info_content',
            field=models.TextField(blank=True, verbose_name='Infos'),
        ),
        migrations.AddField(
            model_name='weeklymails',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Intro'),
        ),
        migrations.AddField(
            model_name='weeklymails',
            name='konzert',
            field=models.TextField(blank=True, verbose_name='Konzert'),
        ),
        migrations.AddField(
            model_name='weeklymails',
            name='sonstiges',
            field=models.TextField(blank=True, verbose_name='Sonstiges'),
        ),
        migrations.AddField(
            model_name='weeklymails',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Gesendet')], default='draft', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='weeklymails',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
