# Generated by Django 5.0.3 on 2024-03-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info_mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklymails",
            name="html_file",
            field=models.FileField(blank=True, upload_to="html_files/"),
        ),
    ]
