# Generated by Django 5.0.3 on 2026-03-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_mail', '0002_newslettersettings_weeklymails_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersettings',
            name='km_appointments_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Konzertmeister Termine-URL'),
        ),
        migrations.AlterField(
            model_name='newslettersettings',
            name='km_requests_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Konzertmeister Anfragen-URL'),
        ),
    ]
