# Generated by Django 5.0.3 on 2024-03-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info_mail", "0002_weeklymails_html_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklymails",
            name="reference",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
