# Generated by Django 5.0.3 on 2024-03-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info_mail", "0003_alter_weeklymails_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklymails",
            name="week",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="weeklymails",
            name="year",
            field=models.IntegerField(unique=True),
        ),
    ]
