# Generated by Django 5.0.3 on 2026-03-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_mail', '0003_newslettersettings_url_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersettings',
            name='mmv_newsletter_month',
            field=models.CharField(blank=True, help_text='Anzeigename des aktuellen MMV-Newsletter-Monats, z. B. "März" oder "April"', max_length=20, verbose_name='MMV Newsletter Monat'),
        ),
        migrations.AddField(
            model_name='newslettersettings',
            name='mmv_newsletter_url',
            field=models.URLField(blank=True, help_text='Monatlich wechselnder Brevo-Link zum aktuellen MMV-Newsletter', max_length=500, verbose_name='MMV Newsletter-URL'),
        ),
    ]
