# Generated by Django 5.0.3 on 2024-03-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info_mail", "0004_alter_weeklymails_week_alter_weeklymails_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklymails",
            name="week",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weeklymails",
            name="year",
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="weeklymails",
            unique_together={("week", "year")},
        ),
    ]
