# Generated by Django 5.0.3 on 2026-03-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_mail', '0004_newslettersettings_mmv_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersettings',
            name='default_test_email',
            field=models.EmailField(blank=True, help_text='Wird im Compose-Bereich als Vorbelegung für den Test-Versand angezeigt.', max_length=254, verbose_name='Standard Test-Versand E-Mail'),
        ),
    ]
