# Generated by Django 5.0.3 on 2026-03-22 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('date', models.DateTimeField(verbose_name='Datum & Uhrzeit')),
                ('venue', models.CharField(max_length=255, verbose_name='Veranstaltungsort')),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preis Erwachsene (€)')),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preis Kinder (€)')),
                ('max_tickets', models.PositiveIntegerField(verbose_name='Maximale Ticketanzahl')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv (Vorverkauf offen)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='concert_posters/', verbose_name='Konzertplakat (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konzert',
                'verbose_name_plural': 'Konzerte',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='E-Mail-Adresse')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon (optional)')),
                ('adult_count', models.PositiveIntegerField(default=0, verbose_name='Anzahl Erwachsene')),
                ('child_count', models.PositiveIntegerField(default=0, verbose_name='Anzahl Kinder')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=8, verbose_name='Gesamtpreis (€)')),
                ('notes', models.TextField(blank=True, verbose_name='Anmerkungen (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bestellt am')),
                ('status', models.CharField(choices=[('ausstehend', 'Ausstehend'), ('bestaetigt', 'Bestätigt'), ('storniert', 'Storniert')], default='ausstehend', max_length=20, verbose_name='Status')),
                ('confirmation_code', models.CharField(editable=False, max_length=12, unique=True, verbose_name='Bestätigungscode')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tickets.concert', verbose_name='Konzert')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
