# Generated by Django 5.0.3 on 2026-03-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='max_tickets',
        ),
        migrations.AddField(
            model_name='concert',
            name='max_adults',
            field=models.PositiveIntegerField(default=0, verbose_name='Max. Erwachsenen-Tickets'),
        ),
        migrations.AddField(
            model_name='concert',
            name='max_children',
            field=models.PositiveIntegerField(default=0, verbose_name='Max. Kinder-Tickets (bis 12 Jahre)'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='child_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preis Kinder bis 12 Jahre (€)'),
        ),
    ]
