# Generated by Django 5.0.3

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_replace_max_tickets_with_per_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='color_primary',
            field=models.CharField(
                default='#0d1b2a',
                max_length=7,
                validators=[django.core.validators.RegexValidator(
                    message='Geben Sie eine gültige Hex-Farbe ein (z.B. #0d1b2a).',
                    regex='^#[0-9A-Fa-f]{6}$',
                )],
                verbose_name='Primärfarbe',
            ),
        ),
        migrations.AddField(
            model_name='concert',
            name='color_accent',
            field=models.CharField(
                default='#c9a84c',
                max_length=7,
                validators=[django.core.validators.RegexValidator(
                    message='Geben Sie eine gültige Hex-Farbe ein (z.B. #0d1b2a).',
                    regex='^#[0-9A-Fa-f]{6}$',
                )],
                verbose_name='Akzentfarbe',
            ),
        ),
        migrations.AddField(
            model_name='concert',
            name='color_background',
            field=models.CharField(
                default='#f5f0e8',
                max_length=7,
                validators=[django.core.validators.RegexValidator(
                    message='Geben Sie eine gültige Hex-Farbe ein (z.B. #0d1b2a).',
                    regex='^#[0-9A-Fa-f]{6}$',
                )],
                verbose_name='Hintergrundfarbe',
            ),
        ),
    ]
