# Generated by Django 5.0.3 on 2026-03-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_concert_capacity_display_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Bezahlt'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='max_adults',
            field=models.PositiveIntegerField(verbose_name='Max. Erwachsenen-Tickets'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='max_children',
            field=models.PositiveIntegerField(verbose_name='Max. Kinder-Tickets (bis 12 Jahre)'),
        ),
    ]
