# Generated by Django 5.0.3 on 2026-03-29 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_ticketorder_abendkasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='source_order',
            field=models.ForeignKey(blank=True, help_text='Nur bei automatisch erstellten Abendkasse-Zusatztickets gefüllt: Verweis auf die Vorbestellung, bei deren Einlass Extratickets hinzugefügt wurden.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_orders', to='tickets.ticketorder', verbose_name='Ursprungsbestellung'),
        ),
    ]
