# Generated by Django 5.0.3 on 2026-03-12 08:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year for this order template (e.g., 2026)', unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only orders with active template can be submitted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Template',
                'verbose_name_plural': 'Order Templates',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='OrderMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Grillwurst mit Pommes Frites'", max_length=255)),
                ('category', models.CharField(choices=[('food', 'Speisen'), ('drink', 'Getränke')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in EUR', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.IntegerField(default=0, help_text='Order in which items appear in the form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='orders.ordertemplate')),
            ],
            options={
                'verbose_name': 'Order Menu Item',
                'verbose_name_plural': 'Order Menu Items',
                'ordering': ['category', 'position'],
                'unique_together': {('template', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the company placing the order', max_length=255)),
                ('contact_name', models.CharField(help_text='Name of person making the order', max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20)),
                ('arrival_time', models.CharField(blank=True, help_text="Expected arrival time (e.g., '12:30')", max_length=5)),
                ('payment_method', models.CharField(choices=[('invoice', 'Rechnung an folgende Adresse'), ('pickup', 'Zahlung bei Abholung (bar oder EC-Karte)')], max_length=50)),
                ('invoice_address', models.TextField(blank=True, help_text="Only required if payment_method is 'invoice'")),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special requests')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('confirmed', 'Bestätigt')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(help_text='Which year/menu this order is for', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.ordertemplate')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at time of order (snapshot from menu)', max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.order')),
                ('menu_item', models.ForeignKey(help_text='Reference to menu item (read-only for historical purposes)', on_delete=django.db.models.deletion.PROTECT, to='orders.ordermenuitem')),
            ],
            options={
                'verbose_name': 'Order Line Item',
                'verbose_name_plural': 'Order Line Items',
                'ordering': ['menu_item__category', 'menu_item__position'],
                'unique_together': {('order', 'menu_item')},
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('template', 'company_name'), name='unique_order_per_company_per_year'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('template', 'company_name')},
        ),
    ]
